---
title: "cscb_qaqc"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })

output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: false
    number_sections: true
    highlight: pygments 
    theme: cosmo
    code_folding: hide
    
---
# First chunk
## First chunk, level 2
```{r setup, include=TRUE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE,echo = F)
email = 1
local_tz = 'Africa/Nairobi'

source('r_scripts/load.R') #libraries
source('r_scripts/UPAS_functions.R') #functions to clean, plot, summarize


```



# Load UPAS data
## Cleaning rules
* Import UPAS metadata, run some diagnostics.  Check for flow issues and run durations.
``` {r load-data, cache = FALSE, echo = FALSE}

# UPAS data import and check
upasfilepath <- "~/Dropbox/World Bank CSCB Field Folder/Field Data/UPAS Data"

file_list_upas <- list.files(upasfilepath, pattern='.txt|.TXT', full.names = T,recursive = T) %>% 
  grep("DIAGNOSTIC", ., ignore.case = TRUE, value = TRUE, invert = TRUE)  %>% 
  grep("2021-3-9_34DACON_C_PS1473_C0214", ., ignore.case = TRUE, value = TRUE, invert = TRUE)  

file_list_upas = file_list_upas[sapply(file_list_upas, file.size) > 10000]

upas_data = rbindlist(lapply(file_list_upas,read_upas),fill=TRUE)


upas_header <- rbindlist(lapply(file_list_upas,read_upas_header)) %>% 
  as.data.frame() %>% 
  dplyr::arrange(UPASlogFilename,StartDateTimeUTC) %>% 
  dplyr::mutate(filename = file_list_upas,
                filename = basename(file_path_sans_ext(filename)),
                file_start_date = as.Date(StartDateTimeUTC),
                CartridgeID = toupper(CartridgeID),
                StartDateTimeLocal = with_tz(StartDateTimeUTC,
                                             tzone="Africa/Nairobi"),
                date_start = date(StartDateTimeLocal)) %>%
  dplyr::filter(!filename %like% "Pilot") %>% 
  dplyr::select(-UPASfirmware,-LifetimeSampleCount,-LifetimeSampleRuntime,-GPSUTCOffset,ProgrammedStartDelay,-AppLock,-AppVersion,
                -StartOnNextPowerUp,-LogInterval,-LogFileMode,-file_start_date,-DutyCycleWindow,-GPSEnabled,-ProgrammedStartDelay,
                -StartBatteryCharge,-EndBatteryCharge,-ShutdownMode,-SampledRuntime,-VolumetricFlowRate,-FlowOffset) %>% 
  tidyr::separate(filename,c("date_file","hhid","location","instrument_id"),sep = "_",extra = "warn",fill = "warn",remove = TRUE)



kable(upas_header,"pipe",caption = "UPAS deployment summary")
# dplyr::filter(date(StartDateTimeLocal) %in% date(field_log$excel_datetime_start) | 
# hour(StartDateTimeLocal) == 0)

```

# Import ODK SUMs
```{r import_odk_sms}

#Only assuming 4 files here - one for start/end, one for download repeat, and two for install repeats.  Make sure this is true!
path_odk_sums_list = list.files("~/Dropbox/World Bank CSCB Field Folder/Field Data/Survey Data (ODK)/SUMS",pattern = ".csv|.CSV",full.names = T) %>% 
  print()


odk_sums_install = read_csv(path_odk_sums_list %>% grep("Download.csv",., ignore.case = TRUE, value = TRUE, invert = FALSE),
                            col_names = TRUE,
                            col_types = cols(.default = col_character())) %>% 
  dplyr::filter(`A_BG_visit1-A7_installdownload` == 2) %>% 
  dplyr::left_join(read_csv(path_odk_sums_list %>% grep("installsum_repeat1",., ignore.case = TRUE, value = TRUE, invert = FALSE),
                            col_names = TRUE,
                            col_types = cols(.default = col_character())) %>% 
                     dplyr::mutate(KEY = PARENT_KEY)) %>% 
  dplyr::left_join(read_csv(path_odk_sums_list %>% grep("installsum_repeat2",., ignore.case = TRUE, value = TRUE, invert = FALSE),
                            col_names = TRUE,
                            col_types = cols(.default = col_character())) %>% 
                     dplyr::mutate(KEY = PARENT_KEY)) %>% 
  tidyr::separate(`A_BG_visit1-A3_HHID`,c("HHID","fieldworker","group")) %>% 
  dplyr::mutate(datetime_install = paste0(`A_BG_visit1-A1_date`,`A_BG_visit1-A2_visittime`)) %>% 
  dplyr::na_if(.,"NANA") %>% 
  dplyr::mutate(datetime_install = as.POSIXct(datetime_install, tz = local_tz, optional = FALSE)) %>% 
  setNames(gsub("[[:punct:]]","", names(.))) 

odk_sums_install_check <- odk_sums_install %>% 
  dplyr::select("HHID","fieldworker","group","datetimeinstall",
                "ABGvisit1gpsLatitude","ABGvisit1gpsLongitude",
                "Status","B1SUMstove","B3SUMID")




odk_sums_download = read_csv(path_odk_sums_list %>% grep("Download.csv",., ignore.case = TRUE, value = TRUE, invert = FALSE),
                             col_names = TRUE,
                             col_types = cols(.default = col_character())) %>% 
  dplyr::filter(`A_BG_visit1-A7_installdownload` == 1) %>% 
  dplyr::left_join(read_csv(path_odk_sums_list %>% grep("downloadsum_repeat.csv",., ignore.case = TRUE, value = TRUE, invert = FALSE),
                            col_names = TRUE,
                            col_types = cols(.default = col_character())) %>% 
                     dplyr::mutate(KEY = PARENT_KEY)) %>% 
  tidyr::separate(`A_BG_visit1-A3_HHID`,c("HHID","fieldworker","group")) %>% 
  dplyr::mutate(datetime_download = paste0(`A_BG_visit1-A1_date`,`A_BG_visit1-A2_visittime`)) %>% 
  dplyr::na_if(.,"NANA") %>% 
  dplyr::mutate(datetime_download = as.POSIXct(datetime_download, tz = local_tz, optional = FALSE)) %>% 
  setNames(gsub("[[:punct:]]","", names(.))) 



odk_sums_download_check <- odk_sums_download %>% 
  dplyr::select(c("HHID","fieldworker","group","datetimedownload",
                  "ABGvisit1gpsLatitude","ABGvisit1gpsLongitude","B3sumid",
                  "B4stove","B13dlsuccess","B151filename",
                  "B16maxtemp","B17mintemp","B18dlfailure"))

```

# Import ODK 
```{r import_odk}

path_odk_start = "~/Dropbox/World Bank CSCB Field Folder/Field Data/Survey Data (ODK)/Instrument Start-End/WBCSCB_InstrumentStart_v2.csv"
path_odk_end = "~/Dropbox/World Bank CSCB Field Folder/Field Data/Survey Data (ODK)/Instrument Start-End/WBCSCB_InstrumentEnd_v1.csv"

odk_start = read_csv(path_odk_start,
                     col_names = TRUE,
                     col_types = cols(.default = col_character())) %>% 
  tidyr::separate(`A_HHInfo-A1_HHID`,c("HHID","fieldworker","group")) %>% 
  dplyr::mutate(datetime_pe = paste0(`C_PE-C2_PEDate`,`C_PE-C3_PETime`),
                datetime_hap = paste0(`B_HAP-B2_HAPdate`,`B_HAP-B3_HAPtime`)) %>% 
  dplyr::na_if(.,"NANA") %>% 
  dplyr::mutate(datetime_pe = as.POSIXct(datetime_pe, tz = local_tz, optional = FALSE),
                datetime_hap = as.POSIXct(datetime_hap, tz = local_tz, optional = FALSE)) %>% 
  setNames(gsub("[[:punct:]]","", names(.))) 


odk_end = read_csv(path_odk_end,
                   col_names = TRUE,
                   col_types = cols(.default = col_character())) %>% 
  tidyr::separate(`A_HHInfo-A1_HHID`,c("HHID","fieldworker","group")) %>% 
  dplyr::mutate(datetime_end = paste0(`A_HHInfo-A2_PE_end_Date`,`A_HHInfo-A3_PE_end_Time`)) %>% 
  dplyr::na_if(.,"NANA") %>% 
  dplyr::mutate(datetime_end = as.POSIXct(datetime_end, tz = local_tz, optional = FALSE)) %>% 
  setNames(gsub("[[:punct:]]","", names(.))) 


odk_check <- odk_start %>% 
  dplyr::select(HHID,fieldworker,group,KEY,datetimepe,datetimehap,CPEC0PEUPASID,BHAPB0HAPUPASID) %>% 
  dplyr::full_join(odk_end %>% 
                     dplyr::select(HHID,fieldworker,group,datetimeend,ESampleEndE24notes))

```

# Import sums file names
```{r import_cooking,echo=FALSE}

# UPAS data import and check
sumsfilepath <- "~/Dropbox/World Bank CSCB Field Folder/Field Data/SUMS Data" 

file_list_sums <- list.files(sumsfilepath, pattern='.CSV|.csv', full.names = T,recursive = T) %>% 
  grep("pilot", ., ignore.case = TRUE, value = TRUE, invert = TRUE)  %>% 
  grep("2021-3-9_34DACON_C_PS1473_C0214", ., ignore.case = TRUE, value = TRUE, invert = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::rename(pathname=".") %>% 
  dplyr::mutate(pathname = as.character(pathname),
                filename = file_path_sans_ext(basename(pathname)),
                filesize_mb = file.size(pathname)/1e6) %>% 
  tidyr::separate(filename,c("HHID","fieldworker","stove","download"))

kable(file_list_sums,caption = "Summary of SUMs files names, and parsing attempt","pipe")
```

# Time tracker data import and save
```{r timetracker}
timetracker_data <- timetracker_import_fun()

```


# Save and send
```{r sendemails,echo=FALSE}


list_of_datasets <- list(
  "UPAS"=upas_header,
  "sums" = file_list_sums,
  "odk_check" = odk_check,
  "odk_sums_download_check" = odk_sums_download_check,
  "odk_sums_install_check" = odk_sums_install_check)

filename = paste0("~/Dropbox/World Bank CSCB Field Folder/Field Data/QA Reports/CSCB_QA_Report_",  Sys.Date(), ".xlsx")
write.xlsx(list_of_datasets,file = filename)

# source('r_scripts/emailfun.R')
# emailfun(email,filename)





```